### ISSUE TITLE
large image problem

### ISSUE THREAD

**Issue by matejc** [goldmann/docker-squash#126]
```
$ docker-squash -t beje:squash --output-path=squashed.tar 080bff34ab92
2016-09-13 13:50:08,222 root         INFO     docker-squash version 1.0.4, Docker 20f81dde, API 1.22...
2016-09-13 13:50:08,222 root         INFO     Using v2 image format
2016-09-13 13:50:08,245 root         INFO     Old image has 12 layers
2016-09-13 13:50:08,245 root         INFO     Checking if squashing is necessary...
2016-09-13 13:50:08,245 root         INFO     Attempting to squash last 12 layers...
2016-09-13 13:50:08,245 root         INFO     Saving image sha256:080bff34ab92e8dd804525ae6f4bb9ebbf76f45ab6ed7f468ebe948445cd2a47 to /tmp/docker-squash-I4MoyD/old/image.tar file...
2016-09-13 13:55:50,625 root         INFO     Image saved!
2016-09-13 13:55:50,625 root         INFO     Unpacking /tmp/docker-squash-I4MoyD/old/image.tar tar file to /tmp/docker-squash-I4MoyD/old directory
2016-09-13 13:58:03,609 root         INFO     Archive unpacked!
2016-09-13 13:58:04,407 root         INFO     Squashing image '080bff34ab92'...
2016-09-13 13:58:04,411 root         INFO     Starting squashing...
2016-09-13 13:58:04,411 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/a81e9bf57d57ea77b61ddd6078a675609748fa1a0e27046b067694bb2d347e67/layer.tar'...
2016-09-13 13:59:18,902 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/50f18a55ae51b71140e5d709d16170d608ef0944994bb256251b0946215e3e02/layer.tar'...
2016-09-13 13:59:18,904 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/93be9be73543462ed80ad539aec8b0fe43da0da32abdab2efbf1af525e941db5/layer.tar'...
2016-09-13 13:59:18,904 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/0e95a2283be05512286b3d88444cfb2010c669c5bf8bcdf4e738a12b89a33b6a/layer.tar'...
2016-09-13 13:59:23,788 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/e1fd594cc6ca6175b8c510e3257351faab908ca550a0688e10e8dbd75912f843/layer.tar'...
2016-09-13 13:59:23,793 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/e3e47292aae8f37f287b4ecf0c98befd42c7e05a27a75e296f28e3f21a04439d/layer.tar'...
2016-09-13 13:59:23,795 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/030c0db7e089abcd66da31ca1c24683d96ff389e8e0513f46b61089274de6620/layer.tar'...
2016-09-13 13:59:23,798 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/e325acda64892aad2067c23b10d39e4e6043f3dc38a316457818a2ff1f8dd586/layer.tar'...
2016-09-13 13:59:23,808 root         INFO     Squashing file '/tmp/docker-squash-I4MoyD/old/e35f039b56649ff8fd0636935f35a7c3ff567e6647b1412e96888dd339799c65/layer.tar'...
2016-09-13 13:59:32,463 root         INFO     Squashing finished!
2016-09-13 14:00:36,797 root         INFO     New squashed image ID is 8d076e26fed04347224890b20f3f80ac6a1281642f047f822d2859039f441ac9
2016-09-13 14:01:41,498 root         INFO     Image available at 'squashed.tar'
2016-09-13 14:03:22,072 root         ERROR    500 Server Error: Internal Server Error ("Untar re-exec error: exit status 1: output: archive/tar: invalid tar header")
2016-09-13 14:03:22,073 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

```
$ cat squashed.tar | docker load
Error response from daemon: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
```

```
$ journalctl -fu docker
Sep 13 14:38:30 matej71 docker[24431]: time="2016-09-13T14:38:30.660858614+02:00" level=error msg="Handler for POST /v1.22/images/load returned error: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header"
```

```
$ docker images -a
# naturally there is no trace of image
```
- this is not the problem of not enough disk space - over 100GB free at the time of running these commands
- docker version is 1.10.3
- the original image is over 26GB, squashed image is 13GB
- if I repeat the process with a smaller image (~150MB), works as expected

**Comment by goldmann** [comment]
Thanks for reporting this! now I wonder how to reproduce it...

**Comment by matejc** [comment]
maybe with ..this Dockerfile
```
FROM busybox
RUN dd if=/dev/zero of=/largefile bs=20M count=1000
CMD tail -f
```

trying to squash right now.. might take a while...

**Comment by matejc** [comment]
it will not change the output size, but will test the whole process with large image/tar problem

**Comment by matejc** [comment]
Dockerfile
```
FROM busybox
RUN dd if=/dev/zero of=/largefile bs=13M count=1000
RUN dd if=/dev/zero of=/largefile bs=13M count=1000
CMD tail -f
```

build:
```
docker build -t largefiles .
```

and then....

```
docker-squash -t largefiles:squash --output-path=squashed.tar daf99ef7f381
2016-09-13 17:27:58,565 root         INFO     docker-squash version 1.0.4, Docker 20f81dde, API 1.22...
2016-09-13 17:27:58,565 root         INFO     Using v2 image format
2016-09-13 17:27:58,572 root         INFO     Old image has 5 layers
2016-09-13 17:27:58,572 root         INFO     Checking if squashing is necessary...
2016-09-13 17:27:58,572 root         INFO     Attempting to squash last 5 layers...
2016-09-13 17:27:58,572 root         INFO     Saving image sha256:daf99ef7f381be8f66b7955bc4c838ce9645e785c124651f03a6cfe46d65b0a1 to /tmp/docker-squash-1VzYxr/old/image.tar file...
2016-09-13 17:33:39,526 root         INFO     Image saved!
2016-09-13 17:33:39,527 root         INFO     Unpacking /tmp/docker-squash-1VzYxr/old/image.tar tar file to /tmp/docker-squash-1VzYxr/old directory
2016-09-13 17:35:59,677 root         INFO     Archive unpacked!
2016-09-13 17:36:00,127 root         INFO     Squashing image 'daf99ef7f381'...
2016-09-13 17:36:00,128 root         INFO     Starting squashing...
2016-09-13 17:36:00,128 root         INFO     Squashing file '/tmp/docker-squash-1VzYxr/old/db1453f5a3d56379d11dcc4e6d8d5f87c48e3ac9a0f0b9276edf8fc549779987/layer.tar'...
2016-09-13 17:37:10,652 root         INFO     Squashing file '/tmp/docker-squash-1VzYxr/old/506e8aaa5ba6fd12603e568f03e55d79f31bb1c68ab504cf01e8fbe1dc7222b2/layer.tar'...
2016-09-13 17:37:10,653 root         INFO     Squashing file '/tmp/docker-squash-1VzYxr/old/0dcdbb9ad7d011ba7e0fc078484373b6b1882ca63558174e3cb7695c004a6e87/layer.tar'...
2016-09-13 17:37:10,702 root         INFO     Squashing finished!
2016-09-13 17:38:15,638 root         INFO     New squashed image ID is 7b926f48469d56f87beed445a2229e7ea135afb29051921d5c20ff05b8a4a98f
2016-09-13 17:39:27,890 root         INFO     Image available at 'squashed.tar'
2016-09-13 17:41:27,171 root         ERROR    500 Server Error: Internal Server Error ("invalid diffID for layer 0: expected "sha256:a82fc39708bb94aa2136f40210dfec9d84f3b2f1a5a13fe41ff70643fe62345a", got "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"")
2016-09-13 17:41:27,171 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

different error but same problem? if I try image size of 16GB with two layers and squashed size of 8GB, then it works. Is this maybe some kind of a docker limitation and not at all problem with docker-squash?

**Comment by matejc** [comment]
same problem with `Docker version 1.12.1, build 23cf638`

**Comment by goldmann** [comment]
I need to find bigger filesystem to test this, if filled all my space up :)

**Comment by rms1000watt** [comment]
Not directly related.. but I've had problems with `docker save`, `docker load`, `docker pull` and `docker push` multiGB docker images in general with errors verrrrry similar to

```bash
invalid diffID for layer 0: expected "sha256:a82fc39708bb94aa2136f40210dfec9d84f3b2f1a5a13fe41ff70643fe62345a", got "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```

My gut thinks it's not a docker-squash issue.

**Comment by goldmann** [comment]
This is actually what I fear. We see some failures i reports that I cannot explain and all of these reporters have to deal with bigger images. It's hard to find the root cause because Docker allows to use multiple storage plugins and configurations. Other problem is that storage to be used for Docker can be configured (formatted for example) in different ways, which is in mostly not tracked anywhere.

**Comment by ximencx** [comment]
i have same iisue,,,you can use "--tmp dir /home/tmp" command solve it

**Comment by KarlCHansen** [comment]
Multiple timeouts and then failure for __huge__ container (160 gigabytes)

Ubuntu 20.04, kernel 5.4.0-47-generic, docker server 19.03.8, 128G ram, 16-core threadripper.  HD is 8Tbyte with 6Tbytes available space.

The issue occurs because just the command `docker save...` takes about **_3 HOURS_** to complete.

I would like to be able to work from just the saved tarfile, e.g. add a commandline option `--tarfile` that allows me to tell squash the tarfile already exists and no need to run initial save. The rest would remain the same, to enable squash to access the meta-data associated with the tarfile.  Other than that, the timeout needs to be specifiable so I can tell squash, "yes, I know this is going to take maybe 4 hours before  you get the tarfile...."

`# docker-squash -v --tmp-dir ./tmp -t local:am2squash local:am2
2020-09-14 20:20:31,908 root         DEBUG    Running version 1.0.8
2020-09-14 20:20:31,908 root         DEBUG    Preparing Docker client...
2020-09-14 20:20:31,908 docker.utils.config DEBUG    Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2020-09-14 20:20:31,908 docker.utils.config DEBUG    Found file at path: /root/.docker/config.json
2020-09-14 20:20:31,908 docker.auth  DEBUG    Found 'auths' section
2020-09-14 20:20:31,908 docker.auth  DEBUG    Found entry (registry='https://index.docker.io/v1/', username='karlchansen')
2020-09-14 20:20:31,932 urllib3.connectionpool DEBUG    http://localhost:None "GET /version HTTP/1.1" 200 757
2020-09-14 20:20:31,935 urllib3.connectionpool DEBUG    http://localhost:None "GET /v1.40/_ping HTTP/1.1" 200 2
2020-09-14 20:20:31,935 root         DEBUG    Docker client ready
2020-09-14 20:20:31,941 urllib3.connectionpool DEBUG    http://localhost:None "GET /v1.40/version HTTP/1.1" 200 757
2020-09-14 20:20:31,942 root         INFO     docker-squash version 1.0.8, Docker afacb8b7f0, API 1.40...
2020-09-14 20:20:31,942 root         INFO     Using v2 image format
2020-09-14 20:20:31,942 root         DEBUG    Using ./tmp as the temporary directory
2020-09-14 20:20:31,944 urllib3.connectionpool DEBUG    http://localhost:None "GET /v1.40/images/local:am2/json HTTP/1.1" 200 None
2020-09-14 20:20:31,947 urllib3.connectionpool DEBUG    http://localhost:None "GET /v1.40/images/sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89/history HTTP/1.1" 200 550
2020-09-14 20:20:31,947 root         INFO     Old image has 3 layers
2020-09-14 20:20:31,948 root         DEBUG    Old layers: ['<missing>', 'sha256:874a52ebaca090783431f022cd0bf5671b823d0192a3de8e6d0db33b943aaad7', 'sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89']
2020-09-14 20:20:31,948 root         DEBUG    We detected number of layers as the argument to squash
2020-09-14 20:20:31,948 root         INFO     Checking if squashing is necessary...
2020-09-14 20:20:31,948 root         INFO     Attempting to squash last 3 layers...
2020-09-14 20:20:31,948 root         DEBUG    Layers to squash: ['<missing>', 'sha256:874a52ebaca090783431f022cd0bf5671b823d0192a3de8e6d0db33b943aaad7', 'sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89']
2020-09-14 20:20:31,948 root         DEBUG    Layers to move: []
2020-09-14 20:20:31,948 root         INFO     Saving image sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 to ./tmp/old directory...
2020-09-14 20:20:31,948 root         DEBUG    Try #1...
2020-09-14 20:30:32,046 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 354, in _save_image
    image = self.docker.get_image(image_id)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 40, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2020-09-14 20:30:32,048 root         WARNING  An error occured while saving the sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 image, retrying...
2020-09-14 20:30:32,048 root         INFO     Saving image sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 to ./tmp/old directory...
2020-09-14 20:30:32,048 root         DEBUG    Try #2...
2020-09-14 20:40:32,063 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 354, in _save_image
    image = self.docker.get_image(image_id)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 40, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2020-09-14 20:40:32,063 root         WARNING  An error occured while saving the sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 image, retrying...
2020-09-14 20:40:32,064 root         INFO     Saving image sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 to ./tmp/old directory...
2020-09-14 20:40:32,064 root         DEBUG    Try #3...
2020-09-14 20:50:32,165 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 354, in _save_image
    image = self.docker.get_image(image_id)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 40, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2020-09-14 20:50:32,166 root         WARNING  An error occured while saving the sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 image, retrying...
2020-09-14 20:50:32,166 root         DEBUG    Cleaning up ./tmp temporary directory
2020-09-14 20:50:32,166 root         ERROR    Couldn't save sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 image!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/cli.py", line 86, in run
    squash.Squash(log=self.log, image=args.image,
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/squash.py", line 61, in run
    return self.squash(image)
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/squash.py", line 91, in squash
    new_image_id=image.squash()
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 73, in squash
    self._before_squashing()
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/v2_image.py", line 15, in _before_squashing
    super(V2Image, self)._before_squashing()
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 212, in _before_squashing
    self._save_image(self.old_image_id, self.old_image_dir)
  File "/usr/local/lib/python3.8/dist-packages/docker_squash/image.py", line 391, in _save_image
    raise SquashError("Couldn't save %s image!" % image_id)
docker_squash.errors.SquashError: Couldn't save sha256:fe8bcdecb0ff16f37a0956b42dbbf7bfbed940b4b3ed41ae4fbcf3760d7b0b89 image!
2020-09-14 20:50:32,166 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
`

**Comment by goldmann** [comment]
@KarlCHansen You can specify how long it should wait before interrupting it using the `DOCKER_TIMEOUT` env variable: https://github.com/goldmann/docker-squash/blob/master/docs/environment_variables.adoc#docker_timeout

**Comment by goldmann** [comment]
I haven't heard back if my suggestion worked - it definitely should :) I'm closing this issue now.
