### ISSUE TITLE
Problem with squashing image - "Read timed out."

### ISSUE THREAD

**Issue by vroomanj** [goldmann/docker-squash#127]
> [root@builder ~]# /opt/anaconda3/bin/docker-squash -t vroomanj/systemuser:squashed --output-path ~/squashed.image 929d5cb581d2
> 2016-09-15 11:39:05,080 root         INFO     docker-squash version 1.0.4, Docker d381c64-unsupported, API 1.22...
> 2016-09-15 11:39:05,081 root         INFO     Using v2 image format
> 2016-09-15 11:39:05,702 root         INFO     Old image has 60 layers
> 2016-09-15 11:39:05,702 root         INFO     Checking if squashing is necessary...
> 2016-09-15 11:39:05,702 root         INFO     Attempting to squash last 60 layers...
> 2016-09-15 11:39:05,703 root         INFO     Saving image sha256:929d5cb581d25e2421fc306a3c574557b93baf9153899b329d79edfc9ad1b140 to /tmp/docker-squash-ty4pzhac/old/image.tar file...
> 2016-09-15 11:49:05,805 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
>     httplib_response = conn.getresponse(buffering=True)
> TypeError: getresponse() got an unexpected keyword argument 'buffering'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
>     httplib_response = conn.getresponse()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 1197, in getresponse
>     response.begin()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/opt/anaconda3/lib/python3.5/socket.py", line 575, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
>     timeout=timeout
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
>     raise value
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
>     chunked=chunked)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/docker_squash/image.py", line 327, in _save_image
>     image = self.docker.get_image(image_id)
>   File "/root/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
>     return f(self, resource_id, _args, *_kwargs)
>   File "/root/.local/lib/python3.5/site-packages/docker/api/image.py", line 18, in get_image
>     res = self._get(self._url("/images/{0}/get", image), stream=True)
>   File "/root/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
>     return f(self, _args, *_kwargs)
>   File "/root/.local/lib/python3.5/site-packages/docker/client.py", line 132, in _get
>     return self.get(url, *_self._set_request_timeout(kwargs))
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 487, in get
>     return self.request('GET', url, *_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, *_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> 2016-09-15 11:49:06,004 root         WARNING  An error occured while saving the sha256:929d5cb581d25e2421fc306a3c574557b93baf9153899b329d79edfc9ad1b140 image, retrying...
> 2016-09-15 11:49:06,004 root         INFO     Saving image sha256:929d5cb581d25e2421fc306a3c574557b93baf9153899b329d79edfc9ad1b140 to /tmp/docker-squash-ty4pzhac/old/image.tar file...
> 2016-09-15 11:59:06,015 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
>     httplib_response = conn.getresponse(buffering=True)
> TypeError: getresponse() got an unexpected keyword argument 'buffering'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
>     httplib_response = conn.getresponse()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 1197, in getresponse
>     response.begin()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/opt/anaconda3/lib/python3.5/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/opt/anaconda3/lib/python3.5/socket.py", line 575, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
>     timeout=timeout
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
>     raise value
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
>     chunked=chunked)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.5/site-packages/docker_squash/image.py", line 327, in _save_image
>     image = self.docker.get_image(image_id)
>   File "/root/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
>     return f(self, resource_id, _args, *_kwargs)
>   File "/root/.local/lib/python3.5/site-packages/docker/api/image.py", line 18, in get_image
>     res = self._get(self._url("/images/{0}/get", image), stream=True)
>   File "/root/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 47, in inner
>     return f(self, _args, *_kwargs)
>   File "/root/.local/lib/python3.5/site-packages/docker/client.py", line 132, in _get
>     return self.get(url, *_self._set_request_timeout(kwargs))
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 487, in get
>     return self.request('GET', url, *_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, *_kwargs)
>   File "/opt/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
> 2016-09-15 11:59:06,016 root         WARNING  An error occured while saving the sha256:929d5cb581d25e2421fc306a3c574557b93baf9153899b329d79edfc9ad1b140 image, retrying...

It is a large image but I didn't have any problems with jwilder docker-squash until Docker version 1.10.

**Comment by goldmann** [comment]
Please bump the timeout with `DOCKER_TIMEOUT` environment variable, see https://github.com/goldmann/docker-squash/blob/master/docs/environment_variables.adoc and try again.

**Comment by vroomanj** [comment]
That worked but then I get this Error at the end:

> 2016-09-15 19:28:05,024 root         ERROR    404 Client Error: Not Found ("b'open /var/lib/docker/tmp/docker-import-018971593/4f428247f330b90c5e22d270ccc220f7ebd1f8f03b49e7f2841d64fae889d083/json: no such file or directory'")

**Comment by goldmann** [comment]
Can you run it with `-v` enabled and paste the log afterwards? You can host the log in gist for easy browsing or here using the triple backtics formatting: ```.

**Comment by vroomanj** [comment]
Will do. The squash is running now! Thanks :+1:

**Comment by vroomanj** [comment]
It creates a log of 146865 lines most of which are mainly DEBUG statements. I have ommited the DEBUG statements from the log because I didn't see an easy way to get that many lines into gist of here.

https://gist.github.com/vroomanj/beb6e142a6c746be6e460b78b6ee734f

**Comment by goldmann** [comment]
I guess I was interested in these DEBUG statements :)

OK, From what I can see you have a very big image. I'm not sure entirely why you have 60 layers there and I'm not sure why do you squash all of them, including previous/base images. In general this is an anti-pattern. I do not think I'll be able to find root cause of this issue. You would need to work on a better Docker image I suspect. You need to optimize it in every single place it is possible and squash only relevant layers. Good practice is to squash content from a single Dockerfile and do not touch layers created by other images.

I see that the load time exceeded 10 minutes. This must be a very large image or a very slow system. I have a feeling that the error message at the end is not necessarily a bug and could be just an error message where the upload failed because the image was too big. I see also that squashing took about 4 hours (?!!!?). Longest squash process I saw took about 10 minutes...

**Comment by vroomanj** [comment]
This is all from 2 Dockerfiles. Unfortunately my Docker image has to be large with everything that is in it for JupyterHub Notebook kernels (primarily compiling the cling kernel explodes the size). The old jwilder/docker-squash used to work wonders but it doesn't function with Docker 1.10+ and it doesn't seem likes it's going to be fixed.

**Comment by goldmann** [comment]
I'm not saying it's not a bug on my side :) I'm saying that with available information I will not be able to find the root cause unfortunately. Additionally this image looks for me suspicious as it's probably can be optimized (for example squashing these two Dockerfiles on their own, leaving 2 layers - squashing everything in most cases does not make sense).

Can you try to squash less layers and see how it goes? If it fails with just a few layers, please report it so we can find the issue. Currently it's looking for a needle in a haystack :(

**Comment by JohnChang2014** [comment]
Hi,

I have similar issue that squash ends up with time out and error of saving image at the end on the environment of EC2 with EBS. Any suggestion?

[ec2-user@ip-172-31-2-28 ~]$ time docker-squash -f 96139b6593c5 -t juypter/persist:squashed1 2bc0cae60eb2
2016-10-31 06:29:41,214 root         INFO     docker-squash version 1.1.0rc1.dev, Docker b9f10c9/1.11.2, API 1.23...
2016-10-31 06:29:41,214 root         INFO     Using v2 image format
2016-10-31 06:29:41,512 root         INFO     Old image has 76 layers
2016-10-31 06:29:42,266 root         INFO     Checking if squashing is necessary...
2016-10-31 06:29:42,266 root         INFO     Attempting to squash last 2 layers...
2016-10-31 06:29:42,266 root         INFO     Saving image sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc to /tmp/docker-squash-1Es1nj/old/image.tar file...
2016-10-31 06:39:42,278 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker_squash/image.py", line 327, in _save_image
    image = self.docker.get_image(image_id)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/api/image.py", line 18, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2016-10-31 06:39:42,284 root         WARNING  An error occured while saving the sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc image, retrying...
2016-10-31 06:39:42,284 root         INFO     Saving image sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc to /tmp/docker-squash-1Es1nj/old/image.tar file...
2016-10-31 06:49:42,287 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker_squash/image.py", line 327, in _save_image
    image = self.docker.get_image(image_id)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/api/image.py", line 18, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2016-10-31 06:49:42,287 root         WARNING  An error occured while saving the sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc image, retrying...
2016-10-31 06:49:42,287 root         INFO     Saving image sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc to /tmp/docker-squash-1Es1nj/old/image.tar file...
2016-10-31 06:59:42,322 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker_squash/image.py", line 327, in _save_image
    image = self.docker.get_image(image_id)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/api/image.py", line 18, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2016-10-31 06:59:42,322 root         WARNING  An error occured while saving the sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc image, retrying...
2016-10-31 06:59:42,323 root         ERROR    Couldn't save sha256:2bc0cae60eb250fd0c14ae5bf33bcab55c6e6d53f4c236f4b87d15a20d66b2dc image!
2016-10-31 06:59:42,323 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!

real	30m1.412s
user	0m0.112s
sys	0m0.024s

**Comment by goldmann** [comment]
@JohnChang2014 Your image contains 76 layers, which is a lot. Docker is not able to prepare a tar archive with all these layers in time. And in time means here 10 minutes -- this is the default setting we use, see https://github.com/goldmann/docker-squash/blob/master/docs/environment_variables.adoc#docker_timeout. This tool tries to fetch the image 3 times and you end up with 30 minutes squash time which in reality is just waiting for Docker.

You have three options:

1. Use faster EC2 instance.
2. Optimize your image.
3. Bump timeout by setting the `DOCKER_TIMEOUT` env variable to something higher than 10 minutes.

**Comment by JohnChang2014** [comment]
Thanks for the reply. I will look into these three options.

One more question is that in the command, I actually tried to squash two latest layers. Would it end up with archiving all 76 layers and timeout?

**Comment by goldmann** [comment]
Yes, Docker does not provide any way to export selected layers.

**Comment by chiselwright** [comment]
Is *9 layers* also too large?

```
-bash-4.2$ /usr/bin/docker-squash -t thingy:99 thingy:99
2017-02-22 13:53:09,253 root         INFO     docker-squash version 1.0.5, Docker 7392c3b/1.12.6, API 1.24...
2017-02-22 13:53:09,254 root         INFO     Using v2 image format
2017-02-22 13:53:09,274 root         INFO     Old image has 9 layers
2017-02-22 13:53:09,274 root         INFO     Checking if squashing is necessary...
2017-02-22 13:53:09,275 root         INFO     Attempting to squash last 9 layers...
2017-02-22 13:53:09,275 root         INFO     Saving image sha256:c2b69ec916c0da4017b45bda46ac17f8c47700f3f07d139f6341666efc824278 to /tmp/docker-squash-HtbNFm/old directory...
2017-02-22 13:54:14,347 root         INFO     Image saved!
2017-02-22 13:54:14,347 root         INFO     Squashing image 'thingy:99'...
2017-02-22 13:54:14,348 root         INFO     Starting squashing...
2017-02-22 13:54:14,348 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/32240ea755de697b669e365d7842cb71d574495a6692ebb07c25f6ef9dfb14cd/layer.tar'...
2017-02-22 13:54:14,586 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/c8db79b64991da3f38283f9c216bbae22b263b818c256f98001e5007d12e3383/layer.tar'...
2017-02-22 13:54:14,586 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/fbae0759850f2f26b80455af669af40cdf24ea8f3fc1fd5eada73c84e8dc1bb3/layer.tar'...
2017-02-22 13:54:14,589 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/650c76a74950b4b90a14cca2ba08a2574f3a9cd207554c1c3fe9a15a6bc03677/layer.tar'...
2017-02-22 13:54:14,623 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/26b0c35540c7c4ff492308ad74e9230c4c6ab6728a1f3efe2a5ff8e688537c51/layer.tar'...
2017-02-22 13:54:14,657 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/a9a1c34b74192f123e2dc3163aede6216ae36dc0dacb2f389f2de2e785334545/layer.tar'...
2017-02-22 13:54:14,658 root         INFO     Squashing file '/tmp/docker-squash-HtbNFm/old/7141bf85c5fed4055f50a6b8bf45bd6b92836d18e03238d0b02b56ebdbe8fc38/layer.tar'...
2017-02-22 13:55:46,475 root         INFO     Squashing finished!
2017-02-22 13:55:54,815 root         INFO     New squashed image ID is cd642372a79a138553e438a9394ec7a59fe6f2ea4f34c26d988280854c958658



2017-02-22 14:06:47,534 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2017-02-22 14:06:47,534 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment]
@chiselwright It's not about the number of layers in most cases, but about size of these layers. Is it a big image? It looks that your host is not capable of loading the squashed image under 10 minutes. Have you tried to bump the https://github.com/goldmann/docker-squash/blob/master/docs/environment_variables.adoc#docker_timeout variable? Have you tried to manually load the squashed image?

**Comment by goldmann** [comment]
Closing because of lack of response.
