### ISSUE TITLE
ERROR: seek of closed file

### ISSUE THREAD

**Issue by NiyunZhou** [goldmann/docker-squash#191]
Using docker-squash on a 21GB docker image, got following error:
```
2019-11-20 16:54:57,014 root         DEBUG    Adding symbolic link '/usr/share/man/sv/man8/delgroup.8.gz' pointing to '/deluser.8.gz' back...
2019-11-20 16:54:57,024 root         DEBUG    Adding symbolic link '/var/lock' pointing to '/run/lock' back...
2019-11-20 16:54:57,032 root         DEBUG    Adding symbolic link '/var/run' pointing to '/run' back...
2019-11-20 16:54:57,049 root         DEBUG    Adding symbolic link '/var/spool/mail' pointing to '/mail' back...
2019-11-20 16:54:57,065 root         DEBUG    Cleaning up /tmp/docker-squash-98tcwtt9 temporary directory
2019-11-20 16:55:01,213 root         ERROR    seek of closed file
Traceback (most recent call last):
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/cli.py", line 87, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development, cleanup=args.cleanup).run()
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/squash.py", line 61, in run
    return self.squash(image)
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/squash.py", line 91, in squash
    new_image_id=image.squash()
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/image.py", line 74, in squash
    ret = self._squash()
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/v2_image.py", line 40, in _squash
    self.layer_paths_to_move)
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/image.py", line 840, in _squash_layers
    squashed_files, added_symlinks)
  File "/home/niccozhou/anaconda3/lib/python3.6/site-packages/docker_squash/image.py", line 639, in _add_file
    squashed_tar.addfile(member, content)
  File "/home/niccozhou/anaconda3/lib/python3.6/tarfile.py", line 1978, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/home/niccozhou/anaconda3/lib/python3.6/tarfile.py", line 255, in copyfileobj
    buf = src.read(remainder)
  File "/home/niccozhou/anaconda3/lib/python3.6/tarfile.py", line 706, in readinto
    buf = self.read(len(b))
  File "/home/niccozhou/anaconda3/lib/python3.6/tarfile.py", line 694, in read
    self.fileobj.seek(offset + (self.position - start))
ValueError: seek of closed file
2019-11-20 16:55:01,296 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

Maybe something wrong with my anaconda?

**Comment by goldmann** [comment]
This is similar to #188, but at least here we have some log :) I'll try to debug it.

**Comment by goldmann** [comment]
Can you make sure you have enough space available in `/tmp` directory? Squashing 21GB image requires a lot of space there. You can also try to use `--tmp-dir` to specify a path on a volume with more space.

**Comment by NiyunZhou** [comment]
Thank you for your reply! I prepared 120GB free space. The space may not be the problem. @goldmann

**Comment by goldmann** [comment]
Just to triple-check - are you sure you have enough space on `/tmp` path? Very often these are not necessarily bound to the root volume? Can you show me the output of `df -h`?

**Comment by NiyunZhou** [comment]
I used "-d" option to reserve tmp files. Here is the space information:
```
niccozhou@ubuntu:/tmp$ du -h --max-depth=1 docker-squash-fwkgxdb8/
21G	docker-squash-fwkgxdb8/old
16G	docker-squash-fwkgxdb8/new
37G	docker-squash-fwkgxdb8/
niccozhou@ubuntu:/tmp$ df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       239G   98G  131G  43% /
```
I think the error comes from some other places. @goldmann

**Comment by goldmann** [comment]
Aye, just wanted to be super-sure that it's not the case, thank you! Will investigate it.

**Comment by yadongwang** [comment]
Maybe this error is not the reason of image size. I encountered the following situations: a 23.8gb (26 layers) image was compressed, which took 2.5hours, and finally compressed successfully; when a 19.9gb (104 layers) image was compressed, the same error was encountered.

**Comment by nicknezis** [comment]
I received this same error. My scenario is as follows...

Buld the following Dockerfile:
```
FROM docker.elastic.co/elasticsearch/elasticsearch:7.14.2
RUN rm -rf /usr/share/elasticsearch/jdk/*
```

I then try to `docker-squash` the resulting image, but it doesn't work. The original image without the `rm -rf` command is squash-able. Why would removing that folder break things? 

p.s. I did notice that the original image installed squashfs. I don't know much about this, but wanted to mention this detail in case it was helpful.

**Comment by kt-315** [comment]
Hi! I found problem. You close tar file and then trying [copy file](https://github.com/goldmann/docker-squash/blob/main/docker_squash/image.py#L843). 
I think need keep opened tar until end this function. I do [this](https://pastebin.com/rMV9wNik), just save descriptor to array and close before return from **_squash_layers**

**Comment by kt-315** [comment]
I think [this same problem](https://github.com/goldmann/docker-squash/issues/202)
