### ISSUE TITLE
Exception - read timeout

### ISSUE THREAD

**Issue by rtarquini** [goldmann/docker-squash#215]
Seeing this error while squashing a 40GB image

2022-10-20 11:25:37,527 root         INFO     docker-squash version 1.0.9, Docker a89b842, API 1.41...
2022-10-20 11:25:37,528 root         INFO     Using v2 image format
2022-10-20 11:25:37,632 root         INFO     Old image has 136 layers
2022-10-20 11:25:37,633 root         INFO     Checking if squashing is necessary...
2022-10-20 11:25:37,633 root         INFO     Attempting to squash last 136 layers...
2022-10-20 11:25:37,633 root         INFO     Saving image sha256:8aeb56db8daa4f840096ef3ce5bf2243d65089081b58630165edb519b6a6a438 to /tmp/docker-squash-3fsgijce/old directory...
2022-10-20 11:35:37,735 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by curea** [comment]
I had this same issue and fixed it by setting an environment variable DOCKER_TIMEOUT to 999999
