### ISSUE TITLE
Destination path tmp/docker-squash already exists

### ISSUE THREAD

**Issue by minhduc24** [goldmann/docker-squash#244]
I used docker-squash version 1.2.0, Docker 25.0.2, API 1.44
docker-squash -f 7 -t image_name image_name with image_name i get fron AWS ECR 
then get this error ERROR Destination path '/tmp/docker-squash-dqv2htwd/new/ba0be36b9c5445d15dd3aca0ee438b8cf0a4b51c2b6a3f34e409da88ea1b369e' already exists.
I tried removing options -f 7 and it worked fine.

**Comment by minhduc24** [comment]
Does anyone know what happened?

**Comment by minhduc24** [comment]
> Can you provide debug logs (with `-v` ) ? Can you provide a reproducer?

DEBUG Running version 1.2.0
2024-03-04 01:13:37,816 common.py:22         DEBUG Preparing Docker client...
2024-03-04 01:13:37,816 config.py:21         DEBUG Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2024-03-04 01:13:37,816 config.py:25         DEBUG Found file at path: /root/.docker/config.json
2024-03-04 01:13:37,816 auth.py:171        DEBUG Found 'auths' section
2024-03-04 01:13:37,816 auth.py:132        DEBUG Found entry (registry='760450950176.dkr.ecr.ap-northeast-1.amazonaws.com', username='AWS')
2024-03-04 01:13:37,818 connectionpool.py:245        DEBUG Starting new HTTP connection (1): localhost:2375
2024-03-04 01:13:37,826 connectionpool.py:547        DEBUG http://localhost:2375 "GET /version HTTP/1.1" 200 821
2024-03-04 01:13:37,828 connectionpool.py:547        DEBUG http://localhost:2375 "GET /v1.44/_ping HTTP/1.1" 200 2
2024-03-04 01:13:37,828 common.py:59         DEBUG Docker client ready
2024-03-04 01:13:37,835 connectionpool.py:547        DEBUG http://localhost:2375 "GET /v1.44/version HTTP/1.1" 200 821
2024-03-04 01:13:37,835 squash.py:54         INFO  docker-squash version 1.2.0, Docker 25.0.2, API 1.44...
2024-03-04 01:13:37,835 squash.py:96         INFO  Using v2 image format
2024-03-04 01:13:37,835 image.py:312        DEBUG Using TMP_DIR as the temporary directory
01:13:37,839 connectionpool.py:547        DEBUG http://localhost:2375 "GET /v1.44/images/760450950176.dkr.ecr.ap-northeast-1.amazonaws.com/fm-ecr-1meg98u82ievw-web-ftt5g5no0t5k:e4cfc8f2-240304010113/json HTTP/1.1" 200 None
2024-03-04 01:13:37,844 connectionpool.py:547        DEBUG http://localhost:2375 "GET /v1.44/images/sha256:760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a/history HTTP/1.1" 200 None
2024-03-04 01:13:37,845 image.py:179        INFO  Old image has 104 layers
2024-03-04 01:13:37,845 image.py:180        DEBUG Old layers: ['<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', 'sha256:760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a']
2024-03-04 01:13:37,845 image.py:189        DEBUG We detected number of layers as the argument to squash
2024-03-04 01:13:37,845 image.py:211        INFO  Checking if squashing is necessary...
2024-03-04 01:13:37,845 image.py:223        INFO  Attempting to squash last 7 layers...
2024-03-04 01:13:37,845 image.py:224        DEBUG Layers to squash: ['<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', 'sha256:760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a']
2024-03-04 01:13:37,845 image.py:225        DEBUG Layers to move: ['<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>', '<missing>']
2024-03-04 01:13:37,845 image.py:371        INFO  Saving image sha256:760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a to TMP_DIR/old directory...
2024-03-04 01:13:37,845 image.py:372        DEBUG Try #1...
2024-03-04 01:18:44,348 connectionpool.py:547        DEBUG http://localhost:2375 "GET /v1.44/images/sha256:760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a/get HTTP/1.1" 200 None
2024-03-04 01:18:44,348 image.py:386        DEBUG Extracting image using iterator over raw data
2024-03-04 01:19:42,568 image.py:406        INFO  Image saved!
2024-03-04 01:19:42,570 image.py:232        INFO  Squashing image '760450950176.dkr.ecr.ap-northeast-1.amazonaws.com/fm-ecr-1meg98u82ievw-web-ftt5g5no0t5k:e4cfc8f2-240304010113'...
2024-03-04 01:19:42,570 v2_image.py:155        DEBUG Reading 'TMP_DIR/old/manifest.json' JSON file...
2024-03-04 01:19:42,571 v2_image.py:155        DEBUG Reading 'TMP_DIR/old/blobs/sha256/760c971c232087c28ac18f5429f2a390b6fba048df6cb5eb7f3ce47ac64e752a' JSON file...
2024-03-04 01:19:42,572 image.py:292        DEBUG Generating list of files in layer 'blobs/sha256/34e4d4479dda156232ca13f83f832971fc1529f055bba6ca95b8ff03f3b1002a'...
2024-03-04 01:19:46,260 image.py:296        DEBUG Done, found 39633 files
2024-03-04 01:19:46,261 image.py:292        DEBUG Generating list of files in layer 'blobs/sha256/e1feb61c6800c7cfa32dbc6313dd43c32879d0fd8c1c788de4cb167447bda43c'...
2024-03-04 01:20:30,463 image.py:963        DEBUG Reducing marker files to be added back...
2024-03-04 01:20:30,463 image.py:978        DEBUG Investigating 'var/www/.wh.build' marker file
2024-03-04 01:20:30,463 image.py:994        DEBUG Removing 0 marker files
2024-03-04 01:20:30,463 image.py:1001       DEBUG Marker files reduced
2024-03-04 01:20:30,463 image.py:558        DEBUG Marker files to add: ['var/www/.wh.build']
2024-03-04 01:20:30,471 image.py:601        DEBUG Adding 'var/www/.wh.build' marker file back...
2024-03-04 01:20:30,471 image.py:922        INFO  Squashing finished!
2024-03-04 01:21:18,757 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/34e4d4479dda156232ca13f83f832971fc1529f055bba6ca95b8ff03f3b1002a'...
2024-03-04 01:21:18,757 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/e1feb61c6800c7cfa32dbc6313dd43c32879d0fd8c1c788de4cb167447bda43c'...
2024-03-04 01:21:18,757 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/402044b7563c7ac23f8332480c48ba8d92cbd381843de249ab0d3bb4fb310438'...
2024-03-04 01:21:18,757 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/15dd80f1cb82bd9114614a4b9f491b0459f82396955e779c05bee20275d7af82'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/fc6c4bb3510d964a9bf4fbefe8c4861b030bd9011572696c66a27d5410d19fba'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/3f8c43dd7a4f97b66cdbb63cef174951f5d6fa44ff45e15094674348986b7275'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/8d97d96d0403e882e38ab58f3b2c85376c386d0c888b5612e53943b5351e1966'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/53f3976ef94f7bbf76995506414e1cd13fa4ee5c360a5af5b5c6e772fecfb358'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/b61f5be1e3d9f49b615e6cf8df079bf89410e25a14bf8c8a3865ebdf0996f4eb'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/4fbc027db34d08093241fed67b9e4e7ef3917229b64f31a21189a6307d2f1aeb'...
2024-03-04 01:21:18,758 image.py:512        DEBUG Moving unmodified layer 'blobs/sha256/689fcdb6ba947cd2e62767f15e416e633f5c79ca110a28bf054a9b13a27f4d7e'...
2024-03-04 01:21:18,760 cli.py:140        ERROR Destination path 'TMP_DIR/new/ba0be36b9c5445d15dd3aca0ee438b8cf0a4b51c2b6a3f34e409da88ea1b369e' already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/cli.py", line 132, in run
    ).run()
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/squash.py", line 99, in run
    return self.squash(image)
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/squash.py", line 134, in squash
    new_image_id = image.squash()
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/image.py", line 84, in squash
    ret = self._squash()
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/v2_image.py", line 97, in _squash
    self._move_layers(
  File "/usr/local/lib/python3.10/dist-packages/docker_squash/image.py", line 513, in _move_layers
    shutil.move(os.path.join(src, layer_id), dest)
  File "/usr/lib/python3.10/shutil.py", line 814, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'TMP_DIR/new/ba0be36b9c5445d15dd3aca0ee438b8cf0a4b51c2b6a3f34e409da88ea1b369e' already exists
2024-03-04 01:21:18,761 cli.py:144        ERROR Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
+ cleanup
+ rm -rf /opt/atlassian/pipelines/agent/build/scripts/../production-config.tar.gz

**Comment by rnc** [comment]
This is rather strange - as if the image itself has two layers with the same id. 

Is the image publicly available so we can examine it or can you share it (even privately)? What about the manifest from the exported tar?

**Comment by goldmann** [comment]
It would be good to get more data. I suggest to export the image as an archive:

```
docker save -o image.tar IMAGE_TAG
```

Then give out the output of this command:

```
tar -tvf image.tar
```

And if possible, please unpack the archive into a directory and upload two metadata files: `manifest.json` and one other JSON file that will be available in the root directory of the unpacked image called something like: `[HASH].json`.

This will greatly help us understand this problem.

**Comment by minhduc24** [comment]
thank you for your support

**Comment by swgu98** [comment]
> It would be good to get more data. I suggest to export the image as an archive:
> 
> ```
> docker save -o image.tar IMAGE_TAG
> ```
> 
> Then give out the output of this command:
> 
> ```
> tar -tvf image.tar
> ```
> 
> And if possible, please unpack the archive into a directory and upload two metadata files: `manifest.json` and one other JSON file that will be available in the root directory of the unpacked image called something like: `[HASH].json`.
> 
> This will greatly help us understand this problem.

I also encountered this problem, how to solve it?
