### ISSUE TITLE
`-t` is required for squash command

### ISSUE THREAD

**Issue by TomasTomecek** [goldmann/docker-squash#66]
using git master:
```
$ PYTHONPATH=$PWD python ./docker_scripts/cli.py squash image
2016-03-29 09:12:22,124 root         INFO     docker-scripts version 1.0.0rc1, Docker c3959b1, API 1.22...
2016-03-29 09:12:22,124 root         INFO     Using v2 image format
Traceback (most recent call last):
  File "./docker_scripts/cli.py", line 109, in <module>
    run()
  File "./docker_scripts/cli.py", line 105, in run
    cli.run()
  File "./docker_scripts/cli.py", line 91, in run
    args.func(args)
  File "./docker_scripts/cli.py", line 32, in run_squash
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development).run()
  File "/home/tt/g/docker-scripts/docker_scripts/squash.py", line 59, in run
    return self.squash(image)
  File "/home/tt/g/docker-scripts/docker_scripts/squash.py", line 71, in squash
    new_image_id = image.squash()
  File "/home/tt/g/docker-scripts/docker_scripts/image.py", line 66, in squash
    self._before_squashing()
  File "/home/tt/g/docker-scripts/docker_scripts/v2_image.py", line 15, in _before_squashing
    super(V2Image, self)._before_squashing()
  File "/home/tt/g/docker-scripts/docker_scripts/image.py", line 143, in _before_squashing
    self.image_name, self.image_tag = self._parse_image_name(self.tag)
  File "/home/tt/g/docker-scripts/docker_scripts/image.py", line 361, in _parse_image_name
    if ':' in image and '/' not in image.split(':')[-1]:
TypeError: argument of type 'NoneType' is not iterable
```

Once I specified `-t`, I got pass this error.

**Comment by goldmann** [comment]
Thanks, I'll look at it.

**Comment by TomasTomecek** [comment]
Thanks Marek!
