### ISSUE TITLE
issue running docker-squash with docker host setup with docker-machine

### ISSUE THREAD

**Issue by rhim** [goldmann/docker-squash#88]
Folks,

I have a local vm that I setup using docker-machine --driver generic. Here is my env:
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.3:2376"
export DOCKER_CERT_PATH="/Users/rhim/.docker/machine/machines/ubuntu-local"
export DOCKER_MACHINE_NAME="ubuntu-local"

When I run docker-squash, I get the following error, and can't seem to figure out the reason. Any help will be appreciated.

```
2016-04-25 10:37:47,805 root         DEBUG    Running version 1.0.0rc4
2016-04-25 10:37:47,805 root         DEBUG    Preparing Docker client...
2016-04-25 10:37:47,823 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): 192.168.99.3
2016-04-25 10:37:47,835 root         ERROR    Could not create Docker client, please make sure that you specified valid parameters in the 'DOCKER_HOST' environment variable.
2016-04-25 10:37:47,835 root         ERROR    Error while creating the Docker client: Error while fetching server API version: hostname '192.168.99.3' doesn't match 'localhost'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/docker_squash/cli.py", line 62, in run
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir, development=args.development).run()
  File "/Library/Python/2.7/site-packages/docker_squash/squash.py", line 29, in __init__
    self.docker = common.docker_client(self.log)
  File "/Library/Python/2.7/site-packages/docker_squash/lib/common.py", line 41, in docker_client
    raise Error("Error while creating the Docker client: %s" % e)
Error: Error while creating the Docker client: Error while fetching server API version: hostname '192.168.99.3' doesn't match 'localhost'
2016-04-25 10:37:47,838 root         ERROR    Execution failed, consult logs above. If you think this is our fault, please file an issue: https://github.com/goldmann/docker-squash/issues, thanks!
```

**Comment by goldmann** [comment]
What `docker-py` version you use? `pip freeze | grep docker`.

Related: https://github.com/docker/docker-py/pull/1013

**Comment by rhim** [comment]
docker-compose==1.4.1
docker-py==1.3.1
docker-squash==1.0.0rc4
dockerpty==0.3.4

**Comment by goldmann** [comment]
And that's the issue. You have a very old version. Please upgrade it to latest version and try again.

**Comment by rhim** [comment]
Yup. That was it. And upgrade fixed it.

Thanks. I will close the issue.

**Comment by goldmann** [comment]
Awesome!

**Comment by goldmann** [comment]
In fact, I probably should add a requirement for minimal version of this dependency, so I consider this still as a bug.

I'll reopen this issue and close it once I fix it.

**Comment by TomasTomecek** [comment]
@goldmann glad you solved it

I would suggest doing a requirement like this: `docker-py>=1.7.2` -- there were lots of SSL fixes related to this in the release and that release should be available on RHEL, Fedora (not even mentioning PyPI since you can get latest greatest from there).

**Comment by goldmann** [comment]
Aye, this is what I'm going to do.
