### ISSUE TITLE
Read time out 

### ISSUE THREAD

**Issue by jlafourc** [goldmann/docker-squash#93]
Hi,

I tried to sqash an images which is quite big (SIZE 24.57 GB) and in then end I have : 
```

2016-05-23 14:04:34,442 root         INFO     docker-squash version 1.0.0rc5, Docker 20f81dd, API 1.22...
2016-05-23 14:04:34,443 root         INFO     Using v2 image format
2016-05-23 14:04:34,532 root         INFO     Old image has 48 layers
2016-05-23 14:04:34,532 root         INFO     Checking if squashing is necessary...
2016-05-23 14:04:34,533 root         INFO     Attempting to squash last 48 layers...
2016-05-23 14:04:34,533 root         INFO     Saving image sha256:a8e53a7a7c3a2ce08d997b2c91209602d5069c6648579cfac750af2ec88bc5ad to /tmp/docker-squash-KFngpJ/old/image.tar file...
2016-05-23 14:14:34,695 root         ERROR    UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/docker_squash/image.py", line 324, in _save_image
    image = self.docker.get_image(image_id)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 17, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=600)
2016-05-23 14:14:34,770 root         WARNING  An error occured while saving the sha256:a8e53a7a7c3a2ce08d997b2c91209602d5069c6648579cfac750af2ec88bc5ad image, retrying...
2016-05-23 14:14:34,770 root         INFO     Saving image sha256:a8e53a7a7c3a2ce08d997b2c91209602d5069c6648579cfac750af2ec88bc5ad to /tmp/docker-squash-KFngpJ/old/image.tar file...
```

Looks like somebody ran into it #51 (sorry you just closed that one)
```

$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 113
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 102
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.963 GiB
Name: gigogne.dsi-cocktail.fr
ID: AGYX:6WG5:B2BQ:ZBKM:MUA7:APO6:IGMD:L5WG:Z75I:ZULH:NED5:QOU3
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

The timout says 600 seconds. Is there any way to increase the timeout duration ? 

Thx 

Julien

**Comment by goldmann** [comment]
Sure, specify the `DOCKER_TIMEOUT` environment variable: https://github.com/goldmann/docker-squash/blob/master/docs/environment_variables.adoc#docker_timeout

Closing.

**Comment by jlafourc** [comment]
Oooops sorry ! Should have read the docs more carefully !

**Comment by goldmann** [comment]
Just one note - after looking at the size of your image - I suspect it could be optimized a lot. I'm not sure how you create this image, but it's way to big, spend some time on it.
